### ISSUE TITLE
CSV: GoDaddy SQL hosting: spatial types and functions are not available

### ISSUE THREAD

**Issue by flaretechcc** [NewSpring/Excavator#104]
I'm getting this error message when using Excavator to import my Family.csv file.

"Transform Data,"System.InvalidOperationException: Spatial types and functions are not available for this provider because the assembly 'Microsoft.SqlServer.Types' version 10 or higher could not be found. 
   at System.Data.Entity.SqlServer.SqlTypesAssemblyLoader.GetSqlTypesAssembly()
   at System.Data.Entity.SqlServer.SqlSpatialServices.GeometryFromText(String wellKnownText)
   at System.Data.Entity.Spatial.DbGeometry.FromText(String wellKnownText)
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.InitializeSpatialTypeDefaultMap()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.TryGetDefaultValue(PrimitiveType primitiveType, Object& defaultValue)
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.GetPropagatorResultForPrimitiveType(PrimitiveType primitiveType, PropagatorResult& result)
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.Visit(EdmMember node)
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.CreateEntitySetPlaceholder(EntitySet entitySet)
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.CreatePlaceholder(EntitySetBase extent)
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.Visit(DbScanExpression node)
   at System.Data.Entity.Core.Common.CommandTrees.DbScanExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateExpressionVisitor`1.Visit(DbExpression expression)
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.Visit(DbProjectExpression node)
   at System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
   at System.Data.Entity.Core.Mapping.Update.Internal.Propagator.Propagate(UpdateTranslator parent, EntitySet table, DbQueryCommandTree umView)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<ProduceDynamicCommands>d__a.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateCommandOrderer..ctor(IEnumerable`1 commands, UpdateTranslator translator)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ProduceCommands()
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing)
   at Rock.Data.DbContext.SaveChanges()
   at Rock.Model.LocationService.Get(String street1, String street2, String city, String state, String postalCode, String country)
   at Excavator.CSV.CSVComponent.LoadFamily(CsvDataModel csvData)
   at Excavator.CSV.CSVComponent.TransformData(String importUser)
   at Excavator.ProgressPage.bwImportData_DoWork(Object sender, DoWorkEventArgs e)"

 

It's consistent only when I'm importing the Family.csv file and only when there is some form of address field information. I've already checked with my hosting provider (GoDaddy) to make sure that i'm not looking for something that isn't available. Its a shared hosting plan so I can't just manually install CLR Types on the server (although it should be there already anyway). I didnt know if an update broke something with Excavator or if i'm just arranging something wrong... Thanks in advance for any help! (i'm hoping the answer isn't just.. "get vps". I'm also aware that the Rock team doesn't think very highly of GoDaddy's hosting but so far this is the first problem i've had and the addresses work fine if I manually enter them in the browser while making a new family.)

**Update** 12/30/14

I re-downloaded Excavator and now I get this error when I try to import the Family.csv file:

12/31/2014 12:14:51 AM,Transform Data,"System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.RegSvrEnum, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.SqlServer.RegSvrEnum, Version=11.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'

**Update** 1/1/15

I'm back to the originally posted error. I read through some other  posts and found that the "could not load file" error had to to do with a permissions issue with the dll files.

**Comment by dcs619** [comment]
I can embed the SqlServer.Types assembly in Excavator, but I'm hesitant to proclaim that as a long-term fix.  Have you had any trouble with addresses geocoding via manual entry?  What version of SQL are you running with GoDaddy?

**Comment by flaretechcc** [comment]
Manual entry works great. I have a team that put several hundred addresses in yesterday (manually..) because I didn't know for sure if this problem would get resolved. I believe the SQL version is 2012. Thank you for all your hard work with this project!

**Comment by dcs619** [comment]
Gotcha...sorry it didn't work!  Hopefully if someone else has this issue I can track down what's happening.
