### ISSUE TITLE
1.3 Family Address Error

### ISSUE THREAD

**Issue by arranf** [NewSpring/Excavator#120]
```
"System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at SafeDirectoryCatalog..ctor(String directory, Type baseType)
   at Rock.Extension.Container`2.Refresh()
   at Rock.Address.VerificationContainer.<.cctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Rock.Model.LocationService.Verify(Location location, Boolean reVerify)
   at Rock.Model.LocationService.Get(String street1, String street2, String city, String state, String postalCode, String country)
   at Excavator.CSV.CSVComponent.LoadFamily(CsvDataModel csvData)
   at Excavator.CSV.CSVComponent.TransformData(String importUser)
   at Excavator.ProgressPage.bwImportData_DoWork(Object sender, DoWorkEventArgs e)"
```

**Comment by arranf** [comment]
I've spent a while looking at this, I've not figured out why this exception is being thrown still. I figured I'd contribute what I've eliminated so far anyway. 

This is definitely an error with Excavator on MK 3.0 rather than an error with my .csv. It works perfectly using the develop branch on MK 2.0. When you upgrade to 3.0 and then use the develop branch (plus 3.0 mapping and dlls) then the error creeps in even if you just use two lines of import on a fresh install and DB.

I've tried copying the rock.dll again just to check it wasn't that. It's not the additional mappings as the altered mappings had nothing to do with the family.csv. The only thing it could otherwise be on the Excavator side of things is potentially an error with the rockwpf.dll

I can't see any changes in 3.0 to locationService.Get so I don't suspect it's that line. I'm wondering whether the changes to the groups in 3.0 are causing some of the lines below to be set incorrectly.

```
                    Location primaryAddress = locationService.Get( famAddress, famAddress2, famCity, famState, famZip, famCountry );
                    if ( primaryAddress != null )
                    {
                        var primaryLocation = new GroupLocation();
                        primaryLocation.LocationId = primaryAddress.Id;
                        primaryLocation.IsMailingLocation = true;
                        primaryLocation.IsMappedLocation = true;
                        primaryLocation.GroupLocationTypeValueId = homeLocationTypeId;
                        newGroupLocations.Add( primaryLocation, rowFamilyId );
                    }
```

**Comment by dcs619** [comment]
@arranf I can confirm this is a bug in 1.3.2.  However, the problem is with the way MEF components are being loaded, not with the actual address lookup.  You should be able to fix the problem by removing the import component you're NOT using (in this case, Excavator.F1.dll).

I've filed an issue with the core team to get this fixed.
