### ISSUE TITLE
Exception on imported people when adding to groups

### ISSUE THREAD

**Issue by islandross** [NewSpring/Excavator#150]
We have a problem where people that are imported through Excavator if added to a group will make the Group Viewer Member List page throw an exception. We are using Excavator on 4.1 runtime and Rock version 4.1. Wondering if there is something missing in the imported person's records that can cause this.

```
<System><Provider Name="ASP.NET 4.0.30319.0"/><EventID>1309</EventID><Level>2</Level><Task>0</Task><Keywords>Keywords</Keywords><TimeCreated SystemTime="2016-04-14T05:37:48Z"/><EventRecordID>626529796</EventRecordID><Channel>Application</Channel><Computer>RD000D3A809054</Computer><Security/></System><EventData><Data>3005</Data><Data>An unhandled exception has occurred.</Data><Data>4/14/2016 5:37:48 AM</Data><Data>4/14/2016 5:37:48 AM</Data><Data>1b9afe8481d342608444289f9b17cf69</Data><Data>5209</Data><Data>24</Data><Data>0</Data><Data>/LM/W3SVC/187088040/ROOT-1-131048253940379786</Data><Data>Full</Data><Data>/</Data><Data>D:\home\site\wwwroot\</Data><Data>RD000D3A809054</Data><Data></Data><Data>4464</Data><Data>w3wp.exe</Data><Data>IIS APPPOOL\islandrock</Data><Data>NullReferenceException</Data><Data>Object reference not set to an instance of an object.
   at RockWeb.Blocks.Groups.GroupMemberList.&lt;&gt;c__DisplayClass49.&lt;BindGroupMembersGrid&gt;b__39(GroupMember m)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RockWeb.Blocks.Groups.GroupMemberList.BindGroupMembersGrid(Boolean selectAll)
   at RockWeb.Blocks.Groups.GroupMemberList.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

</Data><Data>https://rock.islandecc.hk:443/page/113?GroupId=7193&amp;ExpandedIds=151</Data><Data>/page/113</Data><Data>116.48.136.108</Data><Data>cheryl.lui@islandecc.hk</Data><Data>True</Data><Data>Forms</Data><Data>IIS APPPOOL\islandrock</Data><Data>27</Data><Data>IIS APPPOOL\islandrock</Data><Data>False</Data><Data>   at RockWeb.Blocks.Groups.GroupMemberList.&lt;&gt;c__DisplayClass49.&lt;BindGroupMembersGrid&gt;b__39(GroupMember m)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RockWeb.Blocks.Groups.GroupMemberList.BindGroupMembersGrid(Boolean selectAll)
   at RockWeb.Blocks.Groups.GroupMemberList.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
</Data></EventData></Event></Events>
```

**Comment by islandross** [comment]
The problem came from having blank ConnectionStatus on the imported data, which is a required field in Rock 4.0. Connection Status is shown when hovering the mouse over a person's name in the Group Members list on the Group Viewer page and the ConnectionStatusValueId field is not expected to be null. 

Not sure if this will be considered an issue, so I will leave it for the developers to close this if considered a non issue.

**Comment by dcs619** [comment]
Thanks @islandross I'll take a look.
