### ISSUE TITLE
F1: Unable to save additional AttributeValue when it's already set

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Excavator#92]
Reported by @bwitting

I am having trouble with other duplicates too. Here's the latest:

System.Data.SqlClient.SqlException: Cannot insert duplicate key row in object 'dbo.AttributeValue' with unique index 'IX_AttributeIdEntityId'. The duplicate key value is (1661, 34844). The statement has been terminated.
I'm trying to figure out exactly what in the import is causing that by doing a few pieces at a time.

**Comment by bwitting** [comment]
@dcs619 Hey David, looked at the suggestion above and am still having an error on importing communication values (see below). When this happens, it halts the import. Is there a way to skip and keep going when this error occurs?  Or any other way to avoid it?  Let me know if there is any other data I can give you.  

I'm still trying to get an import from our F1 data to complete successfully.  I'm being pushed to launch Rock March 1.

Thanks! 



>1/14/2015 9:44:04 PM,Transform Data,"System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert duplicate key row in object 'dbo.AttributeValue' with unique index 'IX_AttributeIdEntityId'. The duplicate key value is (2350, 8646).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- End of inner exception stack trace ---
   at Rock.Data.DbContext.WrapTransaction(Action action)
   at Excavator.F1.F1Component.SaveCommunication(List`1 newNumberList, List`1 updatedPersonList) in c:\Users\bwitting2\Desktop\Excavator-master\Excavator.FellowshipOne\Maps\Communication.cs:line 234
   at Excavator.F1.F1Component.MapCommunication(IQueryable`1 tableData) in c:\Users\bwitting2\Desktop\Excavator-master\Excavator.FellowshipOne\Maps\Communication.cs:line 206
   at Excavator.F1.F1Component.TransformData(String importUser) in c:\Users\bwitting2\Desktop\Excavator-master\Excavator.FellowshipOne\F1Component.cs:line 194
   at Excavator.ProgressPage.bwImportData_DoWork(Object sender, DoWorkEventArgs e) in c:\Users\bwitting2\Desktop\Excavator-master\Excavator\ProgressPage.xaml.cs:line 127"

**Comment by dcs619** [comment]
I have Excavator improvements scheduled in a couple of weeks (we're setting
up a production env) but I'll see if I can get to it sooner.

The preferred method of setting attribute values is to call
person.LoadAttributes() first, but I need to test how efficient that is
with 200k people.

**Comment by bwitting** [comment]
@dcs619 great, I appreciate it! Let me know if/how I can be of any assistance.
